import assert from "node:assert/strict";
import test from "node:test";
import type { RepositoryModel } from "../src/repository/model.js";
import { createSnapshot } from "../src/repository/snapshot.js";
import { runNativeDiagnostics, diagnosticsByName } from "../src/analysis/diagnostic-runner.js";
const snapshot=createSnapshot("o/r","a".repeat(40),[{path:"a.ts",sha:"1",size:1},{path:"b.ts",sha:"2",size:1},{path:"c.ts",sha:"3",size:1},{path:"d.ts",sha:"4",size:1}],"2026-01-01T00:00:00.000Z");
const model:RepositoryModel={snapshot,fileFacts:[
{file:"a.ts",dependencies:[],symbols:[{name:"BraceService",file:"a.ts",kind:"class",exported:true,line:1}],effects:[{file:"a.ts",kind:"hooks",detail:"Foundry hooks",line:2,symbol:"BraceService"}],states:[{namespace:"fc",key:"brace",file:"a.ts",kind:"foundry-flag",operation:"setFlag",access:"write",namespaceResolved:true,keyResolved:true,line:3}]},
{file:"b.ts",dependencies:[],symbols:[{name:"brace_service",file:"b.ts",kind:"function",exported:true,line:1}],effects:[{file:"b.ts",kind:"foundry-document",detail:"Foundry documents",line:2,symbol:"brace_service"}],states:[{namespace:"fc",key:"brace",file:"b.ts",kind:"foundry-flag",operation:"setFlag",access:"write",namespaceResolved:true,keyResolved:true,line:3}]},
{file:"c.ts",dependencies:[],symbols:[],effects:[{file:"c.ts",kind:"native-execution",detail:"Native execution",line:2,symbol:"<module>"}],states:[]},{file:"d.ts",dependencies:[],symbols:[],effects:[],states:[]}],
dependencies:[{file:"a.ts",from:"a.ts",to:"b.ts",specifier:"./b",kind:"import",line:1},{file:"b.ts",from:"b.ts",to:"a.ts",specifier:"./a",kind:"import",line:1},{file:"c.ts",from:"c.ts",to:"a.ts",specifier:"./a",kind:"import",line:1},{file:"d.ts",from:"d.ts",to:"a.ts",specifier:"./a",kind:"import",line:1}],unresolvedDependencies:[{file:"d.ts",specifier:"./missing",kind:"import",line:2,external:false,candidates:["missing.ts"]}],symbols:[{name:"BraceService",file:"a.ts",kind:"class",exported:true,line:1},{name:"brace_service",file:"b.ts",kind:"function",exported:true,line:1}],effects:[{file:"a.ts",kind:"hooks",detail:"Foundry hooks",line:2,symbol:"BraceService"},{file:"b.ts",kind:"foundry-document",detail:"Foundry documents",line:2,symbol:"brace_service"},{file:"c.ts",kind:"native-execution",detail:"Native execution",line:2,symbol:"<module>"}],states:[{namespace:"fc",key:"brace",file:"a.ts",kind:"foundry-flag",operation:"setFlag",access:"write",namespaceResolved:true,keyResolved:true,line:3},{namespace:"fc",key:"brace",file:"b.ts",kind:"foundry-flag",operation:"setFlag",access:"write",namespaceResolved:true,keyResolved:true,line:3}]};
test("native diagnostics consume the shared model",()=>{const results=runNativeDiagnostics(model);assert.equal(results.length,8);const by=diagnosticsByName(results);assert.ok(by.get("dependency-graph")?.findings.some((f:any)=>f.code==="DEPENDENCY_CYCLE"));assert.ok(by.get("dependency-graph")?.findings.some((f:any)=>f.code==="UNRESOLVED_LOCAL_DEPENDENCY"));assert.ok(by.get("symbol-families")?.findings.some((f:any)=>f.code==="DISTRIBUTED_EXPORTED_SYMBOL_FAMILY"));assert.ok(by.get("state-namespaces")?.findings.some((f:any)=>f.code==="MULTI_WRITER_STATE_SURFACE"));assert.equal(by.get("runtime-signal-map")?.summary.signals,2);assert.ok((by.get("integration-surface-atlas")?.summary.candidates as number)>0);assert.equal(by.get("contract-map")?.summary.contracts,0);});
