import assert from "node:assert/strict";
import test from "node:test";
import { buildFailureEvidence, classifyFailureStage } from "../src/core/run/failure-evidence.js";
import { NativeOrchestrator } from "../src/core/run/orchestrator.js";
import { buildRequestEnvelope } from "../src/core/run/request-envelope.js";
function request(){return{schema_version:2,id:"scan-a",scope_lock:{original_user_instruction:"Route Scan through native execution.",authorized_deliverables:["Route Scan"],authorized_paths:["scripts/a.js","scripts/b.js"],forbidden_expansions:["No menu redesign"]},description:"label a",planning_goal:"Route Scan through native execution.",acceptance_criteria:["Native Scan executes","Targeting preserved"],non_goals:["No menu redesign"],policy:{allowed_paths:["scripts/a.js","scripts/b.js"]},operations:[{type:"replace_text",path:"scripts/a.js",search:"old",replace:"new"}]}}
test("Request Envelope preserves semantic identity across relabeling",()=>{const base=request(),relabeled={...base,id:"scan-b",description:"label b"},changed={...base,planning_goal:"Route Scan through alternate execution."};const a=buildRequestEnvelope(base),b=buildRequestEnvelope(relabeled),c=buildRequestEnvelope(changed);assert.equal(a.request.fingerprint,b.request.fingerprint);assert.notEqual(a.request.fingerprint,c.request.fingerprint);assert.equal(a.intent.acceptance_criteria.length,2);assert.ok(a.scope.operation_paths.includes("scripts/a.js"));assert.match(a.envelope_fingerprint,/^[a-f0-9]{64}$/)});
test("Native orchestrator admits, advances, and closes a run",()=>{const orchestrator=new NativeOrchestrator(),run=orchestrator.admitRequest({repository:"owner/repo",request:request(),requestPath:"dev_scripts/github-filepatcher.json"});assert.equal(run.state,"READY");orchestrator.bindRequestCommit(run.runId,"1".repeat(40));orchestrator.observeWorkflow(run.runId,"in_progress","Apply FilePatcher");assert.equal(run.state,"EXECUTING");orchestrator.observeWorkflow(run.runId,"in_progress","Validate diff");assert.equal(run.state,"VALIDATING");orchestrator.observeWorkflow(run.runId,"in_progress","Commit verified patch");assert.equal(run.state,"PROMOTING");orchestrator.complete(run.runId,{conclusion:"success",triggeringSha:"1".repeat(40),resultCommitSha:"2".repeat(40)});assert.equal(run.state,"SUCCEEDED");assert.equal(run.stateRecord.permitted_next_action,"none");assert.equal(run.stateRecord.validation_closed,true);assert.equal(run.stateRecord.assistant_capabilities.permitted_actions.length,0)});
test("Native orchestrator records bounded terminal failure evidence",()=>{const orchestrator=new NativeOrchestrator(),run=orchestrator.admitRequest({repository:"owner/repo",request:request(),requestPath:"dev_scripts/github-filepatcher.json"}),evidence=buildFailureEvidence({workflow:"GitHub FilePatcher",stage:"Validate diff",scopePaths:["scripts/a.js"],logText:"Error: mismatch\n at scripts/a.js:12\nProcess exited with code 1"});orchestrator.complete(run.runId,{conclusion:"failure",triggeringSha:"1".repeat(40),resultCommitSha:"1".repeat(40),workflow:"GitHub FilePatcher",failureEvidence:evidence});assert.equal(run.state,"FAILED");assert.equal(run.stateRecord.failure?.failure_class,"validation_failure");assert.equal(run.stateRecord.permitted_next_action,"modify_request")});
test("failure stage classifier preserves authoritative categories",()=>{assert.equal(classifyFailureStage("Commit verified patch"),"promotion_failure");assert.equal(classifyFailureStage("Repository audit"),"validation_failure");assert.equal(classifyFailureStage("Patch corridor"),"planning_failure")});
