import assert from "node:assert/strict";
import test from "node:test";
import { buildNativeFailureEvidence,classifyFailureStage } from "../src/core/run/failure-evidence.js";
import { NativeOrchestrator } from "../src/core/run/orchestrator.js";
import { buildRequestEnvelope } from "../src/core/run/request-envelope.js";
function request(){return{schema_version:2,id:"scan-a",scope_lock:{original_user_instruction:"Route Scan through native execution.",authorized_deliverables:["Route Scan"],authorized_paths:["scripts/a.js"],forbidden_expansions:["No menu redesign"]},description:"label a",planning_goal:"Route Scan through native execution.",acceptance_criteria:["Native Scan executes"],non_goals:["No menu redesign"],policy:{allowed_paths:["scripts/a.js"]},operations:[]}}
test("Request Envelope preserves semantic identity across relabeling",()=>{const base=request(),relabeled={...base,id:"scan-b",description:"label b"},changed={...base,planning_goal:"Route Scan through alternate execution."};const a=buildRequestEnvelope(base),b=buildRequestEnvelope(relabeled),c=buildRequestEnvelope(changed);assert.equal(a.request.fingerprint,b.request.fingerprint);assert.notEqual(a.request.fingerprint,c.request.fingerprint);assert.equal(a.kind,"chrypck_request_envelope")});
test("Native orchestrator advances and closes without workflow observation",()=>{const orchestrator=new NativeOrchestrator(),run=orchestrator.admitRequest({repository:"owner/repo",request:request(),requestPath:"mcp://chrypck_plan"});assert.equal(run.state,"READY");orchestrator.bindRequestCommit(run.runId,"1".repeat(40));orchestrator.transition(run.runId,"EXECUTING");orchestrator.transition(run.runId,"VALIDATING");orchestrator.transition(run.runId,"PROMOTING");orchestrator.succeedNative(run.runId,"2".repeat(40),"v".repeat(64));assert.equal(run.state,"SUCCEEDED");assert.equal(run.stateRecord.validation_closed,true)});
test("Native orchestrator records bounded native failure evidence",()=>{const orchestrator=new NativeOrchestrator(),run=orchestrator.admitRequest({repository:"owner/repo",request:request(),requestPath:"mcp://chrypck_plan"}),evidence=buildNativeFailureEvidence("validation",new Error("mismatch"),[{path:"scripts/a.js"}]);orchestrator.failNative(run.runId,evidence);assert.equal(run.state,"FAILED");assert.equal(run.stateRecord.failure?.failure_class,"validation_failure")});
test("failure stage classifier preserves native categories",()=>{assert.equal(classifyFailureStage("promotion"),"promotion_failure");assert.equal(classifyFailureStage("validation"),"validation_failure");assert.equal(classifyFailureStage("patch corridor"),"planning_failure")});
