import { createServer,type IncomingMessage,type ServerResponse } from "node:http";
import { timingSafeEqual } from "node:crypto";
import { createMcpHandler,McpServer } from "@modelcontextprotocol/server";
import { toNodeHandler } from "@modelcontextprotocol/node";
import * as z from "zod/v4";
import { loadConfig } from "./config.js";
import { GitHubRestTransport,GitHubTransportError } from "./adapters/github/client.js";
import { GitHubRepositoryAdapter } from "./adapters/github/repository-adapter.js";
import { PolicyError } from "./core/policy/errors.js";
import { NativeMcpService } from "./mcp/service.js";
import { createBuiltinProjectProfileRegistry } from "./project/builtin-profiles.js";
const config=loadConfig(),transport=new GitHubRestTransport(config.githubToken,config.githubApiVersion),repositoryAdapter=new GitHubRepositoryAdapter(transport,{maxTextFileBytes:config.maxTextFileBytes,maxRepositoryFiles:config.maxRepositoryFiles}),projectProfiles=createBuiltinProjectProfileRegistry(),nativeService=new NativeMcpService(repositoryAdapter,{allowedRepositories:config.allowedRepositories,defaultTargetRef:config.defaultTargetRef,maxMutationFileBytes:config.maxMutationFileBytes,projectProfiles});
function jsonToolResult(value:unknown,isError=false){return{content:[{type:"text" as const,text:JSON.stringify(value,null,2)}],...(isError?{isError:true}:{})}}
function normalizeError(error:unknown):Record<string,unknown>{if(error instanceof PolicyError)return{code:error.code,message:error.message,...error.details};if(error instanceof GitHubTransportError)return{code:"GITHUB_TRANSPORT_ERROR",status:error.status,method:error.method,apiPath:error.apiPath,message:error.message};return{code:"CHRYPCK_ERROR",message:error instanceof Error?error.message:String(error)}}
async function toolBoundary<T>(operation:()=>Promise<T>|T){try{return jsonToolResult(await operation())}catch(error){return jsonToolResult(normalizeError(error),true)}}
const edit=z.discriminatedUnion("type",[z.object({type:z.literal("create_file"),path:z.string().min(1),content:z.string()}),z.object({type:z.literal("replace_file"),path:z.string().min(1),content:z.string()}),z.object({type:z.literal("replace_exact"),path:z.string().min(1),search:z.string().min(1),replace:z.string(),expectedOccurrences:z.number().int().positive().optional()}),z.object({type:z.literal("insert_before_exact"),path:z.string().min(1),anchor:z.string().min(1),content:z.string(),expectedOccurrences:z.number().int().positive().optional()}),z.object({type:z.literal("insert_after_exact"),path:z.string().min(1),anchor:z.string().min(1),content:z.string(),expectedOccurrences:z.number().int().positive().optional()}),z.object({type:z.literal("delete_exact"),path:z.string().min(1),search:z.string().min(1),expectedOccurrences:z.number().int().positive().optional()}),z.object({type:z.literal("remove_file"),path:z.string().min(1)}),z.object({type:z.literal("move_file"),from:z.string().min(1),to:z.string().min(1)})]);
const architecture=z.discriminatedUnion("kind",[z.object({kind:z.literal("decompose"),paths:z.array(z.string().min(1)).optional()}),z.object({kind:z.literal("move"),moves:z.array(z.object({from:z.string().min(1),to:z.string().min(1)})).min(1)})]);
const execute=z.union([z.object({run_id:z.string().min(1),authoring_intent:z.object({id:z.string().trim().min(1),objective:z.string().trim().min(1),edits:z.array(edit).min(1)}),commit_message:z.string().trim().min(1).max(200).optional()}),z.object({run_id:z.string().min(1),architecture_approval:z.object({plan_id:z.string().min(1)}),commit_message:z.string().trim().min(1).max(200).optional()})]);
function buildMcpServer():McpServer{const server=new McpServer({name:"chrypck",version:"1.0.0"});server.registerTool("chrypck_plan",{title:"Plan Governed Change",description:"Build compressed diagnostic evidence and a certified corridor. Optional decompose/move modes produce review-required architectural plans without exposing arbitrary repository browsing.",inputSchema:z.object({repository:z.string().min(3),objective:z.string().trim().min(1),base_ref:z.string().trim().min(1).optional(),architecture:architecture.optional()}),annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async input=>toolBoundary(()=>nativeService.plan(input)));server.registerTool("chrypck_context",{title:"Read Certified Context",description:"Return only server-certified Context Pack source expansion; arbitrary repository paths are not accepted.",inputSchema:z.object({run_id:z.string().min(1),segment_id:z.string().min(1).optional()}),annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async input=>toolBoundary(()=>nativeService.context(input)));server.registerTool("chrypck_execute",{title:"Execute Governed Change",description:"Execute typed bounded edits or an explicitly approved server-issued path-move plan through propagation, validation, and atomic publication.",inputSchema:execute,annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:false,openWorldHint:false}},async input=>toolBoundary(()=>nativeService.execute(input)));server.registerTool("chrypck_result",{title:"Read Governed Result",description:"Return bounded native run state, project profile, architecture plan, telemetry, and terminal evidence.",inputSchema:z.object({run_id:z.string().min(1)}),annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async input=>toolBoundary(()=>nativeService.result(input)));return server}
const handler=createMcpHandler(buildMcpServer,{responseMode:"json"}),nodeHandler=toNodeHandler(handler);function constantTimeTokenMatch(actual:string,expected:string):boolean{const a=Buffer.from(actual),e=Buffer.from(expected);return a.length===e.length&&timingSafeEqual(a,e)}function reject(res:ServerResponse,status:number,message:string):void{res.writeHead(status,{"content-type":"application/json; charset=utf-8"});res.end(JSON.stringify({error:message}))}function authorizeHttp(req:IncomingMessage,res:ServerResponse):boolean{if(config.publicHost){const incoming=String(req.headers.host??"").toLowerCase(),hostname=incoming.split(":")[0]??incoming;if(incoming!==config.publicHost&&hostname!==config.publicHost){reject(res,403,"Host is not allowed.");return false}}const origin=String(req.headers.origin??"").trim();if(origin&&config.allowedOrigins.size>0&&!config.allowedOrigins.has(origin)){reject(res,403,"Origin is not allowed.");return false}if(config.mcpBearerToken){const authorization=String(req.headers.authorization??""),expected=`Bearer ${config.mcpBearerToken}`;if(!constantTimeTokenMatch(authorization,expected)){reject(res,401,"Bearer authorization is required.");return false}}return true}
const httpServer=createServer((req,res)=>{const requestUrl=new URL(req.url??"/",`http://${req.headers.host??"localhost"}`);if(requestUrl.pathname==="/healthz"&&req.method==="GET"){res.writeHead(200,{"content-type":"application/json; charset=utf-8"});res.end(JSON.stringify({ok:true,service:"chrypck",version:"1.0.0",execution:"native",repository_visibility:"diagnostic-projection-plus-certified-context",project_profiles:projectProfiles.list().map(profile=>profile.id)}));return}if(requestUrl.pathname!=="/mcp"){reject(res,404,"Not found.");return}if(!authorizeHttp(req,res))return;void nodeHandler(req,res)});httpServer.listen(config.port,config.host,()=>{console.error(`ChryPck listening on http://${config.host}:${config.port}/mcp`);if(!config.mcpBearerToken&&!['127.0.0.1','localhost','::1'].includes(config.host))console.error("WARNING: MCP_BEARER_TOKEN is not configured on a non-loopback bind.")});async function shutdown(signal:string){console.error(`ChryPck received ${signal}; shutting down.`);await handler.close();httpServer.close(()=>process.exit(0))}process.once("SIGINT",()=>void shutdown("SIGINT"));process.once("SIGTERM",()=>void shutdown("SIGTERM"));
