import { createHash } from "node:crypto";
import { PolicyError } from "./errors.js";
export const SCOPE_LOCK_SCHEMA_VERSION = 1;
export const SCOPE_LOCK_KIND = "chrypck_scope_lock";
export interface ScopeViolation { readonly code:string; readonly summary:string; readonly paths?:readonly string[]; }
export interface ScopeLockAuthority { readonly root:"original_user_instruction"; readonly assistant_may_narrow_scope:true; readonly assistant_may_expand_scope:false; readonly obstacle_may_change_means_not_goal:true; readonly expansion_requires_new_explicit_user_authorization:true; }
export interface ScopeLockResult { readonly schema_version:number; readonly kind:typeof SCOPE_LOCK_KIND; readonly state:"LOCKED"|"SCOPE_VIOLATION"; readonly locked:boolean; readonly fingerprint:string|null; readonly objective_fingerprint?:string; readonly lock_id?:string|null; readonly original_user_instruction?:string; readonly authorized_deliverables?:readonly string[]; readonly authorized_paths?:readonly string[]; readonly forbidden_expansions?:readonly string[]; readonly allow_capability_construction?:boolean; readonly authorized_capabilities?:readonly string[]; readonly declared_paths?:readonly string[]; readonly violations:readonly ScopeViolation[]; readonly authority?:ScopeLockAuthority; }
export interface ScopeLock extends ScopeLockResult { readonly state:"LOCKED"; readonly locked:true; readonly fingerprint:string; readonly objective_fingerprint:string; readonly lock_id:string|null; readonly original_user_instruction:string; readonly authorized_deliverables:readonly string[]; readonly authorized_paths:readonly string[]; readonly forbidden_expansions:readonly string[]; readonly allow_capability_construction:boolean; readonly authorized_capabilities:readonly string[]; readonly declared_paths:readonly string[]; readonly authority:ScopeLockAuthority; }
export interface ScopeLockInput { readonly lockId?:string|null; readonly originalUserInstruction:string; readonly authorizedDeliverables:readonly string[]; readonly authorizedPaths?:readonly string[]; readonly forbiddenExpansions?:readonly string[]; readonly allowCapabilityConstruction?:boolean; readonly authorizedCapabilities?:readonly string[]; }
export type ScopeLockRequest=Record<string,any>;
function stable(value:unknown):unknown{if(Array.isArray(value))return value.map(stable);if(value&&typeof value==="object"){const r=value as Record<string,unknown>;return Object.fromEntries(Object.keys(r).sort().map(k=>[k,stable(r[k])]))}return value}
function hash(value:unknown):string{const s=JSON.stringify(stable(value));if(s===undefined)throw new TypeError("Scope Lock fingerprint input must be JSON-serializable.");return createHash("sha256").update(s,"utf8").digest("hex")}
function strings(value:unknown):string[]{const values=Array.isArray(value)?value:value==null?[]:[value];return[...new Set(values.map(x=>String(x).trim()).filter(Boolean))]}
export function normalizeScopeRepositoryPath(value:unknown):string{return String(value??"").trim().replaceAll("\\","/").replace(/^\.\//,"").replace(/\/{2,}/g,"/")}
export function declaredPaths(request:ScopeLockRequest):string[]{const output:unknown[]=[];for(const operation of request?.operations??[]){for(const key of ["path","from","to"] as const)if(operation?.[key])output.push(operation[key]);for(const root of operation?.roots??[])output.push(root)}for(const edit of request?.authoring_intent?.edits??[]){if(edit?.path)output.push(edit.path);if(edit?.from)output.push(edit.from);if(edit?.to)output.push(edit.to)}for(const move of request?.moves??[]){if(move?.from)output.push(move.from);if(move?.to)output.push(move.to)}for(const candidate of request?.candidates??[]){if(candidate?.source)output.push(candidate.source);for(const unit of candidate?.units??[])if(unit?.target)output.push(unit.target)}for(const allowed of request?.policy?.allowed_paths??[])output.push(allowed);return[...new Set(output.map(normalizeScopeRepositoryPath).filter(Boolean))].sort()}
export function pathAuthorized(candidate:string,authorizedPaths:readonly string[]):boolean{return authorizedPaths.some(allowed=>candidate===allowed||candidate.startsWith(`${allowed.replace(/\/$/,"")}/`))}
export function buildScopeLock(request:ScopeLockRequest):ScopeLockResult{const source=request?.scope_lock,violations:ScopeViolation[]=[];if(!source||typeof source!=="object"||Array.isArray(source))return{schema_version:1,kind:SCOPE_LOCK_KIND,state:"SCOPE_VIOLATION",locked:false,fingerprint:null,violations:[{code:"SCOPE_LOCK_REQUIRED",summary:"Every ChryPck request requires an explicit scope_lock rooted in the user's instruction."}]};const original=String(source.original_user_instruction??"").trim(),deliverables=strings(source.authorized_deliverables),authorizedPaths=strings(source.authorized_paths).map(normalizeScopeRepositoryPath).sort(),forbidden=strings(source.forbidden_expansions),caps=strings(source.authorized_capabilities).sort();if(!original)violations.push({code:"USER_OBJECTIVE_REQUIRED",summary:"scope_lock.original_user_instruction must preserve the user's objective."});if(!deliverables.length)violations.push({code:"AUTHORIZED_DELIVERABLE_REQUIRED",summary:"Scope Lock requires at least one user-authorized deliverable."});const declared=declaredPaths(request);if(!authorizedPaths.length&&declared.length)violations.push({code:"AUTHORIZED_PATHS_REQUIRED",summary:"Path-bearing requests must declare authorized_paths in Scope Lock."});const outside=declared.filter(p=>!pathAuthorized(p,authorizedPaths));if(outside.length)violations.push({code:"PATH_SCOPE_EXPANSION",summary:"The request declares repository paths outside the immutable Scope Lock.",paths:outside});const capability=source.allow_capability_construction===true;if(capability&&!caps.length)violations.push({code:"CAPABILITY_AUTHORIZATION_REQUIRED",summary:"Capability construction requires explicit authorized_capabilities."});const projection={schema_version:1,lock_id:String(source.lock_id??"").trim()||null,original_user_instruction:original,authorized_deliverables:deliverables,authorized_paths:authorizedPaths,forbidden_expansions:forbidden,allow_capability_construction:capability,authorized_capabilities:caps};const{schema_version:_v,...fields}=projection;return{schema_version:1,kind:SCOPE_LOCK_KIND,state:violations.length?"SCOPE_VIOLATION":"LOCKED",locked:violations.length===0,fingerprint:hash(projection),objective_fingerprint:hash(original),...fields,declared_paths:declared,violations,authority:{root:"original_user_instruction",assistant_may_narrow_scope:true,assistant_may_expand_scope:false,obstacle_may_change_means_not_goal:true,expansion_requires_new_explicit_user_authorization:true}}}
export function assertScopeLock(request:ScopeLockRequest):ScopeLock{const lock=buildScopeLock(request);if(!lock.locked)throw new PolicyError("SCOPE_VIOLATION",`Scope Lock rejected request: ${lock.violations.map(v=>v.code).join(", ")}`,{scopeLock:lock});return lock as ScopeLock}
export function createScopeLock(input:ScopeLockInput):ScopeLock{return assertScopeLock({scope_lock:{lock_id:input.lockId??null,original_user_instruction:input.originalUserInstruction,authorized_deliverables:input.authorizedDeliverables,authorized_paths:input.authorizedPaths??[],forbidden_expansions:input.forbiddenExpansions??[],allow_capability_construction:input.allowCapabilityConstruction===true,authorized_capabilities:input.authorizedCapabilities??[]},operations:[]})}
export function assertPathInScope(lock:ScopeLockResult,path:string):void{const p=normalizeScopeRepositoryPath(path),allowed=lock.authorized_paths??[];if(allowed.length&&!pathAuthorized(p,allowed))throw new PolicyError("SCOPE_VIOLATION","Path is outside the active Scope Lock.",{path:p,lockId:lock.lock_id??null})}
